[window]
opacity = 0.88

decorations = "Buttonless"

[window.padding]
x = 10
y = 10

[font]
size = 14.0
normal = { family= "Fira Code", style= "Regular"}
bold = { family= "Fira Code", style= "Bold" }
italic = { family= "Fira Code", style= "Italic" }
